In [31]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [32]:
df = pd.read_csv('customer.csv')

In [33]:
df.head()

,age,gender,review,education,purchased
0,30,Female,Average,School,No
1,68,Female,Poor,UG,No
2,70,Female,Good,PG,No
3,72,Female,Good,PG,No
4,16,Female,Average,UG,No


In [34]:
df.describe()

,age
count,50.000000
mean,54.160000
std,25.658161
min,15.000000
25%,30.250000
50%,57.000000
75%,74.000000
max,98.000000


In [35]:
# HERE WE DO HAVE ALL THE COLUMNS AS CATEGORICAL
# WE NEED TO CONVERT THEM INTO NUMERICAL COLUMNS WITH THE HELP OF ORDINAL ENCODING

# BUT WE HAVENT STUDIED ONE HOT ENCODING YET SO WE WILL DO ORDINAL ENCODING FOR NOW

# WE WILL DROP THE AGE AND GENDER AS THEY DONT HAVE ANY ORDERING IN THEM
df = df.iloc[:, 2:]
df.head()


,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [36]:
from sklearn.preprocessing import OrdinalEncoder

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2, random_state=42)  

In [38]:
X_train

,review,education
12,Poor,School
4,Average,UG
37,Average,PG
8,Average,UG
3,Good,PG
6,Good,School
41,Good,PG
46,Poor,PG
47,Good,PG
15,Poor,UG


In [39]:
y_train

12     No
4      No
37    Yes
8      No
3      No
6      No
41    Yes
46     No
47    Yes
15     No
9     Yes
16    Yes
24    Yes
34     No
31    Yes
0      No
44     No
27     No
33    Yes
5     Yes
29    Yes
11    Yes
36    Yes
1      No
21     No
2      No
43     No
35    Yes
23     No
40     No
10    Yes
22    Yes
18     No
49     No
20    Yes
7     Yes
42    Yes
14    Yes
28     No
38     No
Name: purchased, dtype: object

In [40]:
X_test

,review,education
13,Average,School
39,Poor,PG
30,Average,UG
45,Poor,PG
17,Poor,UG
48,Good,UG
26,Poor,PG
25,Good,School
32,Average,UG
19,Poor,PG


In [41]:
y_test

13     No
39     No
30     No
45    Yes
17    Yes
48    Yes
26     No
25     No
32    Yes
19    Yes
Name: purchased, dtype: object

In [42]:
from sklearn.preprocessing import OrdinalEncoder

In [47]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])


In [48]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [49]:
X_train = oe.transform(X_train)

In [50]:
X_train

array([[0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 1.],
       [1., 0.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 0.]])

In [51]:
X_test = oe.transform(X_test)

In [52]:
X_test

array([[1., 0.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [1., 1.],
       [0., 2.]])

In [53]:
oe.categories

[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]

In [54]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()


In [55]:
le.fit(y_train)

LabelEncoder()

In [56]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [57]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [58]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0])

In [60]:
y_test

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1])

In [61]:
## make df from the encoded data
encoded_df = pd.DataFrame(X_train, columns=['Experience', 'Education'])
encoded_df['Target'] = y_train
encoded_df

,Experience,Education,Target
0,0.0,0.0,0
1,1.0,1.0,0
2,1.0,2.0,1
3,1.0,1.0,0
4,2.0,2.0,0
5,2.0,0.0,0
6,2.0,2.0,1
7,0.0,2.0,0
8,2.0,2.0,1
9,0.0,1.0,0
